language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - rustup component add clippy
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --verbose
